name: CI/CD Pipeline

on:
  schedule:
    - cron: '*/1 * * * *' 


jobs:
  job1:
    name: Hello World
    runs-on: windows-latest
    steps:
      - name: echo name
        shell: pwsh
        run: get-computerinfo


