name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  hello-world-name-check:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: echo name
        run: echo "Hello Surya"
      - name: show os details
        run: cat /etc/os-release
