name: CI/CD Pipeline

on: push


jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: |
          pwd
          ls -la
          hostname
      - name: step-2
        uses: actions/checkout@v6.1.0
      - name: step-3
        run : |
          pwd
          ls -la
          hostname


